jsdom/cssstyle

- lib/properties/fontFamily.js
- tests/tests.js
The font shorthand "12em monospace" doesn't parse. The test case should have picked this up, but the validation API call was wrong. The attached PR fixes the test case validation so it now fails, but it doesn't fix the source of the shorthand parsing error.
> Shorthand font style doesn't parse

- lib/parsers.js
- lib/properties/margin.js
- lib/properties/padding.js
- tests/tests.js
This pull request improves the handling of `padding` and `margin`.  They now set and clear the `-top`, `-right`, `-bottom`, and `-left` properties properly, and validate the value they are set to.  It also adds some tests to verify that this works.
As part of the update, the `implicitSetter()` function is simplified, and made more efficient (the `parser` function is only called once on any of the parts).  Also, unneeded empty parts are not retained in the `_values` array.  Finally, `getParts()` now allows multiple spaces as separators.
> Improve handling of padding and margin 

- lib/parsers.js
- lib/properties/margin.js
- lib/properties/marginBottom.js
- lib/properties/marginLeft.js
- lib/properties/marginRight.js
- lib/properties/marginTop.js
- lib/properties/padding.js
- lib/properties/paddingBottom.js
- lib/properties/paddingLeft.js
- lib/properties/paddingRight.js
- lib/properties/paddingTop.js
- tests/tests.js
This pull request adds login to set `padding` and `margin` when one of its sub-properties changes (and all four sub-properties are set).  This should resolve issue #37.  It also adds a new test to check that it does what it is supposed to.  I also fixed some tab-versus-spacing.
> Patch padding margin

- lib/properties/height.js
- lib/properties/width.js
- tests/tests.js
Allow `width` and `height` to be set to `auto`, and add new test to verify the fix.  Resolves issue #40.
> Allow width and height to be set to auto

- lib/parsers.js
- tests/tests.js
Per https://www.quirksmode.org/css/units-values/ the 'ex' unit has widespread cross-browser support, and it's even relied on by Gmail in styling its "quoted text" bars to send within emails. However, it was missing from the parser, causing JSDOM to silently drop any style rule that used ex values - not the easiest thing to debug! We've added a quick fix to the regex, as well as unit tests that fail without the changed regex and succeed with it.
Hopefully this can be a quick merge and minor release!
> Ensure ex length units are correctly parsed

- lib/properties/alignContent.js
- lib/properties/alignItems.js
- lib/properties/flexDirection.js
- lib/properties/flexFlow.js
- lib/properties/flexWrap.js
- lib/properties/justifyContent.js
- tests/tests.js
This will allow dependent projects such as jsdom to keep flex-related values.
> added flex-related properties and a test

- package.json
`rem` is now a valid css unit which should be supported by CSSStyleDeclaration.
See https://developer.mozilla.org/en-US/docs/Web/CSS/length
> Add rem unit to parser

- package.json
- scripts/run_tests.sh
The previous `npm test` script executed a `.sh` file
that isn't natively supported by Windows.
Since the actual code inside the `.sh` is pretty small,
it can be completely embedded inside a `npm` script instead,
making it cross-platform and more straight-forward.
_This is a suggestion, if there are specific reasons why this should be in a `.sh` file as it was, disregard this PR._
> cross-platform `npm test` script

- README.md
- lib/properties/borderSpacing.js
- package.json
- scripts/run_tests.sh
- tests/tests.js
This fix include a test and follow the approach used in [padding.js](https://github.com/chad3814/CSSStyleDeclaration/blob/master/lib/properties/padding.js)
> An alternative fix for PR#47 - Add support for numeric values passed to ‘border-spacing’, e.g. ‘border-spacing: 0’

- lib/parsers.js
- tests/tests.js
Adds the ability to specify lengths using viewport measurements.
Note: does not add the ability to use `vmax`.
> Support vh and vw for lengths

- .travis.yml
- tests/tests.js
The test command deliberately doesn't include linting (it can be very annoying, especially when prototyping). However, we want CI to lint, so `test-ci` is more comprehensive.
> Change the CI command to test-ci

- package.json
Warning should break the build, especially if they come from prettier - we want the code to be neat at all time (without the need for scary red squiggles).
> Set max-warnings to 0 for ESLint

- .travis.yml
v1.2.0 broke some apps running in Node 6 due to use of dangling comma. I would like to prevent that from happening again for future updates.
> Test node versions 6, 8, 10, and 11 in CI

- lib/named_colors.json
- tests/tests.js
Currently setting an element's color style with `transparent` or `currentcolor`, both of which are valid, returns an empty string:
```js
var isValidColor = (colour) => {
var element = document.createElement('div');
element.style.color = colour;
return element.style.color;
};
isValidColor('red'); // 'red'
isValidColor('#f00'); // 'rgb(255, 0, 0)'
isValidColor('rebeccapurple'); // 'rebeccapurple'
isValidColor('transparent'); // ''
isValidColor('currentcolor'); // ''
```
Whereas in Chrome v72: 
```js
var isValidColor = (colour) => {
var element = document.createElement('div');
element.style.color = colour;
return element.style.color;
};
isValidColor('red'); // 'red'
isValidColor('#f00'); // 'rgb(255, 0, 0)'
isValidColor('rebeccapurple'); // 'rebeccapurple'
isValidColor('transparent'); // …
```
> fix: Add missing valid color refs 'transparent' and 'currentcolor'

- .travis.yml
- lib/parsers.js
The existing regex requires a decimal. This matches `1.0`, but not `1`, making `rgba(1, 1, 1, 1)` invalid when it should be considered valid.
Closes #92
> numberRegEx should match whole numbers

- .eslintrc.js
- .gitignore
- .travis.yml
- package-lock.json
- package.json
Update all dependencies including CCSOM which looks like its gotten a few releases.
Drop support for Node 6. Its reached EOL - https://github.com/nodejs/Release
> Update all dependencies

- lib/CSSStyleDeclaration.test.js
- lib/parsers.js
- lib/parsers.test.js
- lib/utils/colorSpace.js
Fix issue https://github.com/jsdom/jsdom/issues/2639. 
Color with decimal alpha values were not recognized.
> Fix parsing of colors with decimal alpha

- .npmignore
Hi!
When looking at the global size of jsdom, I noticed that cssstyle was packaging a lot of unnecessary things. For instance, the generated coverage (1.2Mb) is included in the package.
Before (v2.0.0):
The generated tgz is 149kb.
The unpacked package is 1.43Mb.
Estimated now:
The generated tgz is 32kb.
The unpackage package is 190Kb.
> Ignore everything except lib

- lib/CSSStyleDeclaration.js
- lib/CSSStyleDeclaration.test.js
Part of #89 which is blocking https://github.com/facebook/react/pull/17896.
I did not implement full support since this requires more work and is only partially useful for JSDOM because resolution of values of the css variables requires the cascade. 
Browser behavior: https://codesandbox.io/s/css-custom-properties-access-423ni
> feat: Implement read/write of custom properties

- lib/CSSStyleDeclaration.test.js
- lib/parsers.js
- lib/parsers.test.js
This PR adds basic support for un-computed `calc()` values. 
Closes #100
> Implement basic calc

- lib/CSSStyleDeclaration.test.js
- lib/parsers.js
- lib/properties/margin.js
- lib/properties/padding.js
Per the linked issue in [jsdom](https://github.com/jsdom/jsdom/issues/2504), the following bug exists, where `dom` is a JSDom instance:
```
const elem = dom.window.document.createElement('a');
elem.style.marginTop = '10px';
console.log(elem.style.marginTop); // '10px'
elem.style.marginTop = '';
console.log(elem.style.marginTop); // Expected '', but '10px' received.
```
This PR fixes this bug by specifying that `null` and `empty string` are valid values for subparts of the properties `margin` and `padding`. I've also added tests for the behavior of setting these properties to `undefined` (value should remain as is).
Verified that this behavior (using the repro above) matches the following browser's behavior:
Chrome 119.0.6045.123
Edge 120.0.2186.2
Firefox 120.0b8
Safari 17.1 …
> Handle empty string and null for margin and padding subparts

- package-lock.json
- package.json
- scripts/download_latest_properties.js
We can remove minipass-fetch and use Node.js's built-in fetch() now.
Closes #163.
> Update dev dependencies

- lib/CSSStyleDeclaration.test.js
- lib/parsers.js
- lib/properties/margin.js
- lib/properties/padding.js
This should fix https://github.com/jsdom/jsdom/issues/3372 by allowing to set properties like `marginTop` to an empty string.
> Allow removing indiviual margin/padding properties

- lib/CSSStyleDeclaration.js
- lib/CSSStyleDeclaration.test.js
fixes jsdom/jsdom#3305
According to the spec, [setting a css declaration](https://drafts.csswg.org/cssom/#set-a-css-declaration) "must return true if the serialization of declarations was changed as result of the steps. It may return false otherwise". This information is used when [calling `setProperty`](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-setproperty), "if updated is true, update style attribute for the CSS declaration block."
At the same time for [`cssText` property](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-csstext), there are no conditions for setting the new value
> fix: skip onchange callback if serialized value did not change

- lib/CSSStyleDeclaration.js
180cab17ece0cd3db23a26464eff39038a354a7a removed unnecessary access to the cssText property when there is no onChange callback provided. However, 1f5940b2759605f890039764380b553fad855816 undid that gain by saving the original value for later comparison.
> Re-do the recent performance fix

- lib/properties/margin.js
- lib/properties/padding.js
- test/CSSStyleDeclaration.js
Add support for `calc` for `margin` and `padding`. Other properties such as `width`, `top`, ... already support calc.
More properties should support `calc`, but I haven't included them all in this PR:
- `background-position: calc(100% - 0%) calc(100% - 10%)`. Not included because `parse` function splits on whitespace, but whitespace can also occur inside calc parentheses.
- `border-bottom-width` (and other "length" types): uses `parseLength` (from `parsers.js`), didn't want to change because too many usages. It could be done though, for example `parseMeasurement` already allows `calc`.
This PR should fix https://github.com/jsdom/cssstyle/issues/154
> Add calc support for margin and padding

- lib/CSSStyleDeclaration.js
- lib/parsers.js
- package-lock.json
- package.json
- test/CSSStyleDeclaration.js
- test/parsers.js
Fixes #125, closes #127
Based on #127. Many thanks.
> Support nested var() and nested calc()

- lib/properties/backgroundColor.js
- lib/properties/borderColor.js
- test/CSSStyleDeclaration.js
- test/parsers.js
My attempt at fixing #184. Please feel free to use this code however ends up most useful.
> Use parsers.parseColor() in border-color parsing, like background-color

- lib/parsers.js
- test/CSSStyleDeclaration.js
- test/parsers.js
Fix #103
* Handle escaped char.
* Output URL string with quotes.
Although the unquoted output is valid, all major browsers appear to quote the output.
This is a BREAKING CHANGE
> Update parseUrl function

- lib/properties/backgroundAttachment.js
- lib/properties/backgroundColor.js
- lib/properties/backgroundImage.js
- lib/properties/backgroundPosition.js
- lib/properties/backgroundRepeat.js
- test/CSSStyleDeclaration.test.js
> fix background-* spelling

- .github/workflows/build.yml
- lib/properties/font.js
- package.json
- scripts/generateImplementedProperties.mjs
* `.github/workflows/build.yml`
Drop node v18 and add node v22 as `lts/*`
* `package.json`
Bump `engines.node` to `>=20`
* `lib/properties/font.js`
Switch to Array.prototype.toReversed()
* `scripts/generateImplementedProperties.mjs`
* Switch to `import.meta.dirname`
* Sort generated properties
<ins>Done below</ins>
TODO:
Fix `properties/font.js` after #227 get merged.
TBD:
Should we fix `scripts/generateImplementedProperties.mjs` too?
However, `import.meta.dirname` is not standard.
> Raise minimum Node.js version to v20

- lib/CSSStyleDeclaration.js
- lib/parsers.js
- package-lock.json
- package.json
- test/CSSStyleDeclaration.test.js
- test/parsers.test.js
- test/properties.test.js
Switch to [CSSTree](https://www.npmjs.com/package/css-tree) to improve code quality.
* Add some fixes to CSSStyleDeclaration setter
Related wpts:
* to-upstream
* css/css-syntax/parse-invalid-input.html
* css/cssom
* serialization-CSSDeclaration-with-important.html
* css/css-color
* light-dark-currentcolor-in-color.html
Fails but this is expected. Need to fix getComputedStyle()
> Use css-tree

- lib/properties/flex.js
- test/CSSStyleDeclaration.test.js
Fixes the case in the flex shorthand where the third value isn't an explicit value or dimension, which was causing a parse error when called with (e.g.) `flex: 0 0 auto`
> Fix parsing flex-basis in shorthand flex when not a value
